# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: new-pool

steps:
- script: echo Welcome to my Pipeline
  displayName: 'STAGE-1'

- script: echo this is second stage
  displayName: 'STAGE-2'

- script: echo this is third stage
  displayName: 'stage-3'
